name: heroku-deploy
on:
  push:
    branches:
     - config/ci-cd

jobs:
  deploy-heroku:
    runs-on: ubuntu-latest
    name: heroku deploy
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "alectrion-user-api"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: |
            DB_URL
        env:
          DB_URL: ${{ secrets.DB_URL }}